Update example

diff --git a/example/data/703602/ex01/build b/example/data/703602/ex01/build
--- a/example/data/703602/ex01/build
+++ b/example/data/703602/ex01/build
@@ -1,3 +1,6 @@
 #!/bin/bash
 
+date
+
 echo "Building! 🔧"
+echo "Error! ❌" >&2
